logging:
  receivers:
    my-app-receiver:
      type: files
      include_paths:
        - /var/log/webapplogs/webapp-logs
      record_log_file_path: true
  processors:
    my-app-processor:
      type: parse_json
      time_key: timestamp
      time_format: "%Y-%m-%dT%H:%M:%S.%LZ"
    add_severity:
      type: modify_fields
      fields:
        severity:
          move_from: jsonPayload.level

          map_values:
            "info": "INFO"
            "error": "ERROR"
            "warn": "WARNING"
            "debug": "DEBUG"

  service:
    pipelines:
      default_pipeline:
        receivers: [my-app-receiver]
        processors: [my-app-processor, add_severity]