name: packer-fmt-validate-job

on: 
  pull_request:
    
    branches:
      - main
  
jobs:
  fmt-validate-packer:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup packer 
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: "1.10.1"

      - name: create webapp zip file 
        run: |
          cd ..
          zip -r webapp.zip webapp
          cp webapp.zip webapp/
      
      - name: Initialize packer
        run: packer init googlecompute.pkr.hcl
      
      - name: Format packer template
        run: packer fmt -check googlecompute.pkr.hcl
      
      - name: Validate packer template
        run: packer validate googlecompute.pkr.hcl

        
