name: packer-build-vm-image

on: 
  pull_request:
    
    branches:
      - main
    types:
      - closed

jobs:
  build-image:
    runs-on: ubuntu-latest

    if: ${{ github.event.pull_request.merged == true }}
    steps:

      - name: Checking out code
        uses: actions/checkout@v4

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCLOUD_CRED }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'
      
      - name: Setup packer 
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: "1.10.1"
      
      - name: create webapp zip file 
        run: |
          cd ..
          zip -r webapp.zip webapp
          cp webapp.zip webapp/
      
      - name: Initialize packer
        run: packer init googlecompute.pkr.hcl

      - name: Build image 
        run: packer build googlecompute.pkr.hcl