name: packer-build-vm-image

on: 
  pull_request:
    
    branches:
      - main
    # types:
    #   - closed

jobs:
  build-image:
    runs-on: ubuntu-latest

    # if: ${{ github.event.pull_request.merged == true }}
    steps:

      - name: Checking out code
        uses: actions/checkout@v4

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCLOUD_CRED }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'
      
      - name: Setup packer 
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: "1.10.1"
      
      - name: create webapp zip file 
        run: |
          cd ..
          zip -r webapp.zip webapp
          cp webapp.zip webapp/
      
      - name: Initialize packer
        run: packer init googlecompute.pkr.hcl

      - name: Build image 
        run: packer build -var "image_name=${{secrets.IMAGE_NAME}}" googlecompute.pkr.hcl
              

      - name: Create template based on existing instance
        run: gcloud compute instance-templates create ${{secrets.NEW_INSTANCE_NAME}} \
              --source-instance=${{secrets.SOURCE_INSTANCE}} \
              --source-instance-zone=${{secrets.SOURCE_INSTANCE_ZONE}} \
              --instance-template-region=${{secrets.REGION}} \
              --configure-disk=device-name=${{secrets.DEVICE_NAME}},instantiate-from=custom-image,custom-image="projects/dev-aditya-mysore/global/images/${{secrets.IMAGE_NAME}}"

      - name: Set the template to the managed instance group
        run: gcloud compute instance-groups managed set-instance-template ${{secrets.INSTANCE_GROUP}} \
              --template=projects/dev-aditya-mysore/regions/${{secrets.REGION}}/instanceTemplates/${{secrets.NEW_INSTANCE_NAME}} \
              --region=${{secrets.REGION}}

      - name: Start rolling update
        run: gcloud compute instance-groups managed rolling-action start-update ${{secrets.INSTANCE_GROUP}} \
              --version=template=projects/dev-aditya-mysore/regions/${{secrets.REGION}}/instanceTemplates/${{secrets.NEW_INSTANCE_NAME}} \
              --region=${{secrets.REGION}}

      - name: Wait for the VMs to be updated with new template
        run: gcloud compute instance-groups managed wait-until ${{secrets.INSTANCE_GROUP}} \
              --version-target-reached \
              --region=${{secrets.REGION}}