name: packer-build-vm-image

on: 
  push:
    
    branches:
      - assignment4

jobs:
  build-image:
    runs-on: ubuntu-latest

    steps:
      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCLOUD_CRED }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'
      
      - name: Setup packer 
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: "1.10.1"
      
      - name: create webapp zip file 
        run: |
          cd ..
          zip -r webapp.zip webapp-forked
          cp webapp.zip webapp-forked/
      
      - name: Initialize packer
        run: packer init ../../googlecompute.pkr.hcl

      - name: Build image 
        run: packer build ../../googlecompute.pkr.hcl