name: integration-tests-workflow

on:
  pull_request:
    branches:
      - main

jobs:
  integration-testing:
    runs-on: ubuntu-20.04
        
    steps:
      - name: Checkout branch 
        uses: actions/checkout@v4


      - name: Install dependencies
        run: npm install
      
      - name: Start postgresql service
        run: |
          sudo systemctl start postgresql.service
          pg_isready

      - name: Change user password
        run: sudo -u ${{secrets.USERNAME}} psql -c "ALTER USER ${{secrets.USERNAME}} PASSWORD '${{ secrets.PASSWORD }}';"

      - name: Create database 
        run: sudo -u ${{secrets.USERNAME}} psql -c "CREATE DATABASE ${{secrets.DATABASE_NAME}};"

      - name: Run tests
        run: npm run integration-test
        env:
          DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          DATABASE_HOST: ${{ secrets.DATABASE_HOST }}