name: integration-tests-workflow

on:
  push:
    branches:
      - assignment3

jobs:
  integration-testing:
    runs-on: ubuntu-20.04
    # container: node:16.18

    # services:
    #   postgres:
    #     image: postgres:latest

    #     env:
    #       POSTGRES_DB: postgres
    #       POSTGRES_USER: postgres
    #       POSTGRES_PASSWORD: postgres

    #     ports:
    #       - 5432:5432
        
    #     options: >-
    #       --health-cmd pg_isready
    #       --health-interval 10s
    #       --health-timeout 10s
    #       --health-retries 20
        
        
    
    steps:
      - name: Checkout branch 
        uses: actions/checkout@v4


      - name: Install dependencies
        run: npm install
      
      # - run: sudo service docker start
      - name: Start postgresql service
        run: |
          sudo systemctl start postgresql.service
          pg_isready
      
      - name: Create dtabtase
        run: |
          sudo -u postgres psql --command="SHOW password_encryption;"
      
      - name: Change authentication method
        run: sudo -u postgres psql --command="SELECT version();" --command="\du"

      - name: Set permisson on conf file
        run: sudo chmod 755 /etc/postgresql/16/main/pg_hba.conf

      - name: open conf file
        run: echo "/etc/postgresql/$(ls /etc/postgresql)/main"
      
      # - name: starting docker postgres
      #   run: |
      #     docker run --name some-postgres -e POSTGRES_PASSWORD=postgres -e POSTGRES_DB:example -e POSTGRES_USER:postgres -p 5432:5432 -d postgres
      #     sleep 15
      #     docker ps

      # - name: Sleep and run 
      #   run: |
      #     sleep 20
      #     docker ps

      - name: Run tests
        run: npm run test
        env:
          DATABASE_NAME: example
          USERNAME: postgres
          PASSWORD: postgres
          DATABASE_HOST: 127.0.0.1