name: integration-tests-workflow

on:
  push:
    branches:
      - assignment3

jobs:
  integration-testing:
    runs-on: ubuntu-20.04
        
    steps:
      - name: Checkout branch 
        uses: actions/checkout@v4


      - name: Install dependencies
        run: npm install
      
      # - run: sudo service docker start
      - name: Start postgresql service
        run: |
          sudo systemctl start postgresql.service
          pg_isready

      - name: Change user password
        run: sudo -u postgres psql -c "ALTER USER postgres PASSWORD '${{ secrets.PASSWORD }}';"

      - name: Create database 
        run: sudo -u postgres postgres createdb -h ${{ secrets.DATABASE_HOST }} -e ${{secrets.DATABASE_NAME}}

      - name: Run tests
        run: npm run test
        env:
          DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          DATABASE_HOST: ${{ secrets.DATABASE_HOST }}