name: integration-tests-workflow

on:
  push:
    branches:
      - assignment3

jobs:
  integration-testing:
    runs-on: ubuntu-latest
    container: node:16.18

    services:
      postgres:
        image: postgres

        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres

        ports:
          - 5432:5432
        
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        
        
    
    steps:
      - name: Checkout branch 
        uses: actions/checkout@v4
      - run: echo ${{secrets.USERNAME}}

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test
        env:
          DATABASE_NAME: example
          USERNAME: postgres
          PASSWORD: postgres
          DATABASE_HOST: 127.0.0.1