name: integration-tests-workflow

on:
  push:
    branches:
      - assignment3

jobs:
  integration-testing:
    runs-on: ubuntu-20.04
    # container: node:16.18

    # services:
    #   postgres:
    #     image: postgres:latest

    #     env:
    #       POSTGRES_DB: postgres
    #       POSTGRES_USER: postgres
    #       POSTGRES_PASSWORD: postgres

    #     ports:
    #       - 5432:5432
        
    #     options: >-
    #       --health-cmd pg_isready
    #       --health-interval 10s
    #       --health-timeout 10s
    #       --health-retries 20
        
        
    
    steps:
      - name: Checkout branch 
        uses: actions/checkout@v4

      - name: Setup postgresql
        uses: harmon758/postgresql-action@v1
        with:
          postgresql version: '16'
      
      - name: Check postgresql
        run: sudo systemctl status postgresql

      - name: Install dependencies
        run: npm install
      
      # - run: sudo service docker start
      - name: Start postgresql service
        run: |
          sudo systemctl start postgresql.service
          pg_isready
      

      - name: Run tests
        run: npm run test
        env:
          DATABASE_NAME: example
          USERNAME: postgres
          PASSWORD: postgres
          DATABASE_HOST: 127.0.0.1