name: integration-tests-workflow

on:
  push:
    branches:
      - assignment3

jobs:
  integration-testing:
    runs-on: ubuntu-latest
    container: node:16.18

    services:
      postgres:
        image: postgres:12-alpine

        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        
        ports:
          - 5432:5432
    
    steps:
      - name: Checkout branch 
        uses: actions/checkout@v4
      - run: echo ${{secrets.USERNAME}}

      - name: Install dependencies
        run: npm install
      
      - run : sleep 10

      - name: Run tests
        run: npm run test
        env:
          DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          DATABASE_HOST: ${{ secrets.DATABASE_HOST }}