name: integration-tests-workflow

on:
  push:
    branches:
      - assignment3

jobs:
  integration-testing:
    runs-on: ubuntu-latest
    container: node:16.18

    services:
      postgres:
        image: postgres

        env:
          POSTGRES_PASSWORD: ${{ secrets.PASSWORD }}
          POSTGRES_USER: ${{ secrets.USERNAME }}
          POSTGRES_DB: ${{ secrets.DATABASE_NAME }}
        
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        
        ports:
          - 5432:5432
    
    steps:
      - name: Checkout branch 
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run server
        env:
          DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          DATABASE_HOST: ${{ secrets.DATABASE_HOST }}